language: c

script: cmake ../ && make

install:
 - git clone https://github.com/joyent/libuv.git
 - cd libuv && sh autogen.sh && ./configure --prefix=/usr && make && sudo make install && cd ..
 - sudo apt-get install xterm make gcc bison flex subversion cvs automake1.10 autoconf autotools-dev autoconf-archive libtool gettext libpam0g-dev libfreetype6-dev libpng12-dev zlib1g-dev libjpeg62-dev libtiff4-dev libungif4-dev librsvg2-dev libx11-dev libxcursor-dev libxrender-dev libxrandr-dev libxfixes-dev libxdamage-dev libxcomposite-dev libxss-dev libxp-dev libxext-dev libxinerama-dev libxft-dev libxfont-dev libxi-dev libxv-dev libxkbfile-dev libxres-dev libxtst-dev libltdl7-dev xserver-xephyr libdbus-1-dev liblua5.1-0-dev libasound2-dev libudev-dev libxcb-shape0-dev liburiparser-dev 
 - wget http://download.enlightenment.org/rel/libs/efl/efl-1.9.3.tar.gz && tar -xvzf efl-1.9.3.tar.gz
 - cd efl-1.9.3 && ./autogen.sh --prefix=/usr && make && make install && cd ..
 - mkdir build && cd build
