language: c

script: cmake ../ && make

install:
 - git clone https://github.com/joyent/libuv.git
 - cd libuv && sh autogen.sh && ./configure --prefix=/usr && make && sudo make install && cd ..
 - sudo apt-get install e17-dev liburiparser-dev
 - mkdir build && cd build
