language: c

script: cmake ../ && make

install:
 - sudo apt-get update
 - sudo apt-get install check libluajit-5.1-dev libblkid-dev mount libmount-dev autopoint libfribidi-dev autoconf-archive libtool libpam0g-dev libjpeg-dev libungif4-dev librsvg2-dev libdbus-1-dev liblua5.1-0-dev libasound2-dev libudev-dev liburiparser-dev
 - git clone https://github.com/joyent/libuv.git
 - cd libuv && sh autogen.sh && ./configure --prefix=/usr && make && sudo make install && cd ..
 - git clone http://git.enlightenment.org/core/efl.git
 - cd efl && ./autogen.sh --prefix=/usr --enable-i-really-know-what-i-am-doing-and-that-this-will-probably-break-things-and-i-will-fix-them-myself-and-send-patches-aba --disable-physics --with-x11=none --disable-gstreamer1 --disable-audio && make && sudo make install && cd ..
 - mkdir build && cd build
