#include <Eo.h>
#include <Eina.h>
#include <common.h>
#include "xml_sax_base.eo.h"
#include "amin.eo.h"
#include "amin_machine_spec.eo.h"
#include "amin_machine_spec_document.eo.h"
#include "uriparser/Uri.h"

typedef struct
{

} Amin_Data;

EOLIAN static Efl_Object *
_amin_parse(const Eo *obj, Amin_Data *pd, const char *profile)
{
    UriParserStateA state;
    UriUriA machine_spec_uri;
    state.uri = &machine_spec_uri;
    Amin_Machine_Spec *machine_spec;

    if ( uriParseUriA ( &state, profile ) != URI_SUCCESS )
    {
        /* Failure */
        uriFreeUriMembersA ( &machine_spec_uri );
        machine_spec = efl_add_ref(AMIN_MACHINE_SPEC_CLASS, NULL);
    } else {
        machine_spec = efl_add_ref(AMIN_MACHINE_SPEC_CLASS, NULL); // TODO ADD set_uri function to class.
    }

    // OLD Xinclude logic
    // Eo *xinclude_filter = eo_add_custom(AMIN_XINCLUDE, NULL, set_handler_constructor(machine_spec));


    // This just uses the raw parser to load up the Machine Spec containing the
    // Amin machine configuration / filters to load etc.
    Eo *xml_base = efl_add_ref(XML_SAX_BASE_CLASS, NULL);

    xml_sax_base_handler_set(xml_base, machine_spec);


    EINA_LOG_DBG("Kicking parser into action");
    // TODO Move to struct once declared at completeion of machine_spec.
    Amin_Machine_Spec_Document *spec;

    Eo *result = xml_sax_base_parse_string(xml_base, profile);


    // TODO create streaming writer to stdout etc.
    // return XML string generated by plugged in writer.

}

#include "amin.eo.c"
